// Generated by CoffeeScript 1.10.0
angular.module('RestauranteAPP').directive('listaSubcardapio', function() {
  return {
    restrict: 'E',
    templateUrl: '/static/restaurante/js/application/templates/lista-subcardapio.html',
    controller: 'subcardapioController',
    controllerAs: 'subcardapio_controller'
  };
});
